# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      
      sudo apt-get install \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
      
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      
      sudo add-apt-repository \
         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) \
         stable"
      
      sudo apt-get update
      
      sudo apt-get install docker-ce docker-ce-cli containerd.io

steps:
- script: dotnet build --framework netcoreapp3.1 --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
